# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #    
#                                                                                               #
#                                     Vanilla Challenges                                        #
#                                   Created by eliotesta98                                      #
#                                                                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #   

Configuration:
  # List of Challenges
  Challenges:
    # BlockPlaceChallenge
    BlockPlace:
      TypeChallenge: 'BlockPlaceChallenge'
      # Block you want placed for challenge, if you want all blocks write ALL
      Block: ALL
      # Block you want place the block, if you want all write ALL
      BlockOnPlaced: GRASS_BLOCK
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aBlock Placer Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &ePlace blocks on Grass Block for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    BlockBreaker:
      TypeChallenge: 'BlockBreakChallenge'
      # Block you want break for challenge, if you want all blocks write ALL
      Block: ALL
      # Type of item in main hand for break this blocks, if you want all items write ALL
      ItemInHand: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aBreaker Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eBreak all type of block for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Crafter:
      TypeChallenge: 'CraftingChallenge'
      # Item you want crafting for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aCrafting Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eCraft any item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Cooker:
      TypeChallenge: 'CookerChallenge'
      # Item you want cook for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aCook Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eCook any item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Consumer:
      TypeChallenge: 'ConsumeChallenge'
      # Item you want to consume for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aConsume Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eConsume any item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    ExpCollector:
      TypeChallenge: 'CollectorExpChallenge'
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aCollect Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eCollect Experience for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Killer:
      TypeChallenge: 'KillChallenge'
      # Mob you want to kill for challenge, if you want all mobs write ALL
      Mob: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aKill Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eKill any mob for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Breeder:
      TypeChallenge: 'BreedChallenge'
      # Mob you want to breed for challenge, if you want all mobs write ALL
      Mob: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aBreed Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eBreed mob for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Feeder:
      TypeChallenge: 'FeedChallenge'
      # Item you want to feed for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aFeed Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eEat items or starve for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Shooter:
      TypeChallenge: 'ShootChallenge'
      # Force you want to apply for shoot arrow in challenge, if you want to disable use 0.0
      Force: 1.0
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aShoot Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eShoot arrows at max power for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    JumperHorse:
      TypeChallenge: 'JumpWithHorseChallenge'
      # Power you want to apply for jump with horse in challenge, if you want to disable use 0.0
      Power: 0.5
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aJump With Horse Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eJump with Horse at middle or plus power for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Dyer:
      TypeChallenge: 'ColorSheepChallenge'
      # Color you want to use for challenge, if you want all colors write ALL
      Color: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aColor Sheep Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eColor a Sheep with dye for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Raider:
      TypeChallenge: 'RaidChallenge'
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aRaid Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eWin raid for receive points (1 points for waves)'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Fisher:
      TypeChallenge: 'FishingChallenge'
      # Item you want to fish for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aFishing Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eFishing for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Sprinter:
      TypeChallenge: 'SprintChallenge'
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aSprint Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eSprint for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Mover:
      TypeChallenge: 'MoveChallenge'
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aMove Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eMove for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Damager:
      TypeChallenge: 'DamageChallenge'
      # Cause you want to damage for challenge, if you want all causes write ALL
      Cause: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aDamage Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eTake damage for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Sneaker:
      TypeChallenge: 'SneakChallenge'
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aSneak Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eSneak for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    ItemBreaker:
      TypeChallenge: 'ItemBreakChallenge'
      # Item you want to break for challenge, if you want all items write ALL
      Item: ALL
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aBreak Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eBreak an item for receive points'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
    Absorber:
      TypeChallenge: 'SpongeAbsorbChallenge'
      # Title challenge
      Title: '&c&l[Vanilla Challenge] &aSponge Absorb Challenge'
      # Description of Challenge
      Description: '&c&l[Vanilla Challenge] &eAbsorb fluids with Sponge for receive points (1 point for 1 source)'
      # Reward in blocks EX: IRON_INGOT:16 Type:Quantity NOBODY for no reward
      Reward: 'NOBODY'
  BroadcastMessage:
    # time in minutes 0 to disabled
    TimeTitleChallenges: 10
# Messages
Message:
  commandFooter: '&7(&7&l(&c&l!&7&l)&7) &9&l[] optional value, <> required'
  commandVcReloadHelp: '&e/vc &6<reload> &7command reload Plugin'
  commandVcHelpHelp: '&e/vc &6<help> &7command help for VanillaChallenge Plugin'
  commandVcNextHelp: '&e/vc &6<next> &7go to the next challenge'
  commandVcTopHelp: '&e/vc &6<top> &7for see the top 3'
  commandVcPointsHelp: '&e/vc &6<points> [playerName] &7for see your points or points of another player'
  commandVcClear: '&e/vc &6<clear> &7for clear all Challenges and player Points'

  errorYouAreNotAPlayer: '&cYou are not a player'
  errorCommandNotFound: '&cCommand not found'
  errorNoPerms: '&cInsufficient permission'

  pointsInfo: '&a&l{player} points are {number}'
  actuallyInTop: '&c&l[Vanilla Challenge] &a&lActually in top there are:'
  topPlayers: '&a&l{number}Â° place: {player} with {points} points'
  challengeReward: '&c&l[Vanilla Challenge] &a&lYou complete the challenge and arrive at top 3 players, receive x{number} of {item}'

Debug:
  # Commands time execution
  Commands: false
  # Block Place Event time execution
  BlockPlaceEvent: false
  # Block Break Event time execution
  BlockBreakEvent: false
  # Daily Give Reward Event time execution
  DailyGiveRewardEvent: false
  # Craft Item Event time execution
  CraftItemEvent: false
  # Furnace Cook Event time execution
  FurnaceCookEvent: false
  # Item Consume Event time execution
  ItemConsumeEvent: false
  # Exp Collector Event time execution
  ExpCollectorEvent: false
  # Kill Event time execution
  KillEvent: false
  # Breed Event time execution
  BreedEvent: false
  # Feed Event time execution
  FeedEvent: false
  # Shoot Arrow Event time execution
  ShootArrowEvent: false
  # Jump Horse Event time execution
  JumpHorseEvent: false
  # Color Sheep Event time execution
  ColorSheepEvent: false
  # Raid Event time execution
  RaidEvent: false
  # Fish Event time execution
  FishEvent: false
  # Eat Event time execution
  EatEvent: false
  # Sprint Event time execution
  SprintEvent: false
  # Move Event time execution
  MoveEvent: false
  # Damage Event time execution
  DamageEvent: false
  # Sneak Event time execution
  SneakEvent: false
  # Item Break Event time execution
  ItemBreakEvent: false
  # Sponge Absorb Event time execution
  SpongeAbsorbEvent: false
  # Enabled time execution
  Enabled: false
  # Disabled time execution
  Disabled: false
