# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #    
#                                                                                               #
#                                     Vanilla Challenges                                        #
#                                   Created by eliotesta98                                      #
#                                                                                               #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #   

Configuration:
  #If you want random generation of Challenges
  RandomChallengeGeneration: false


  # If you want reset the player points at the end of every challenge
  ResetPointsAtNewChallenge: false


  # If you want resume points without zero (Ex 1.000 = 1k)
  PointsResume: true


  # Chest for ItemCollectionChallenge
  CollectionChallengeItem:
    Type: CHEST
    Name: "&7Chest Collector"
    Lore:
      - "&7Place this chest and use it for collect items"


  # Points if remain online for x minutes
  OnlinePoints:
    # If You want this feature
    Enabled: false
    # Point at minutes
    Point: 10
    # Every time you want player remain online for give points
    Minutes: 10


  BroadcastMessage:
    # time in minutes 0 to disabled
    TimeTitleChallenges: 10


  Top:
    # if you want yesterday top with broadcast and commands
    YesterdayTop: false


  Hooks:
    PlaceholderAPI: false
    CubeGenerator: false
    

  # If you want use H2 or .yml file for data storage (write H2 or Yaml)
  Database: 'H2'


  Backup:
    Enabled: true
    NumberOfFilesInFolder: 4


# Messages
Messages:
  Prefix: '&eVanillaChallenges  &r'
  Commands:
    Footer: '&7(&7&l(&c&l!&7&l)&7) &9[] optional value, <> required'
    Reload: '   &e/vc &6<reload> &7command reload Plugin'
    Next: '   &e/vc &6<next> &7go to the next challenge'
    Top: '   &e/vc &6<top> &7for see the top 3'
    Points: '   &e/vc &6<points> [playerName] &7for see your points or points of another player'
    Clear: '   &e/vc &6<clear> &7for clear all Challenges and player Points'
    Challenge: '   &e/vc &6<challenge> &7for see the daily challenge selected and time resume'
    Economy: '   &e/vc &6<add|remove> <playername> <points> &7for add or remove points of a player'
    Reward: '   &e/vc &6<reward> &7for receive reward of win'
  Errors:
    YouAreNotAPlayer: '{prefix}&cYou are not a player'
    CommandNotFound: '{prefix}&cCommand not found'
    NoPerms: '{prefix}&cInsufficient permission'
    AlreadyPlacedChest: '{prefix}&7You already placed a chest for Collection Item Challenge'
  PointsInfo: '{prefix}&e{player} &7have &b{number}&7 points'
  ActuallyInTop: '{prefix}&7Actually in top there are:'
  TopPlayers:
    - '&6{number}° &e{player}&7 with &b{points}&7 points'
    - '&7{number}° &e{player}&7 with &b{points}&7 points'
    - '&8{number}° &e{player}&7 with &b{points}&7 points'
  PointsEveryMinutes: '{prefix}&7You collect &b{points}&7 points in &e{minutes}&7 minutes'
  ChallengeReward: '{prefix}&7You complete the challenge and arrive at top 3 players, receive x&b{number}&7 of &e{item}'
  BoostMessage: '{prefix}&5Start boosting!&7 You have &bx{number}&7 points for &e{minutes}&7 minutes'
  BoostMessageSinglePlayer: '{prefix}&5Start personal boosting!&7Only you have &bx{number}&7 points for &e{minutes}&7 minutes'
  PointsRemainForBoosting: '{prefix}&7Remain &b{points}&7 points for start next boost!'
  PointsRemainForBoostingSinglePlayer: '{prefix}&7Remain &b{points}&7 points for start next personal boost!'
  ChatWord: '{prefix}&7Write this word for receive &b{points}&7 points: &5{word}'
  CorrectAnswer: '{prefix}&e{player} &7write the correct answer!'
  PointsAdd: '{prefix}&b{points} &7points added at &e{player}'
  PointsRemove: '{prefix}&b{points} &7points removed at &e{player}'

Debug:
  # Commands debug
  Commands: false
  # Block Place Event debug
  BlockPlaceEvent: false
  # Block Break Event debug
  BlockBreakEvent: false
  # Daily Give Reward Event debug
  DailyGiveRewardEvent: false
  # Craft Item Event debug
  CraftItemEvent: false
  # Furnace Cook Event debug
  FurnaceCookEvent: false
  # Item Consume Event debug
  ItemConsumeEvent: false
  # Exp Collector Event debug
  ExpCollectorEvent: false
  # Kill Event debug
  KillEvent: false
  # Breed Event debug
  BreedEvent: false
  # Feed Event debug
  FeedEvent: false
  # Shoot Arrow Event debug
  ShootArrowEvent: false
  # Jump Horse Event debug
  JumpHorseEvent: false
  # Color Sheep Event debug
  ColorSheepEvent: false
  # Raid Event debug
  RaidEvent: false
  # Fish Event debug
  FishEvent: false
  # Eat Event debug
  EatEvent: false
  # Sprint Event debug
  SprintEvent: false
  # Move Event debug
  MoveEvent: false
  # Damage Event debug
  DamageEvent: false
  # Sneak Event debug
  SneakEvent: false
  # Item Break Event debug
  ItemBreakEvent: false
  # Sponge Absorb Event debug
  SpongeAbsorbEvent: false
  # Harvest Event debug
  HarvestEvent: false
  # Egg Event debug
  EggThrowEvent: false
  # Enchant Item Event debug
  EnchantItemEvent: false
  # Chat Event debug
  ChatEvent: false
  # Item Collector Event debug
  ItemCollector: false
  # Inventory Challenge Event debug
  Inventory: false
  # Vehicle Move Challenge Event debug
  VehicleMoveEvent: false
  # Jump Challenge Event debug
  JumpEvent: false
  # Dye Challenge Event debug
  DyeEvent: false
  # Online Point give debug
  OnlinePoint: false
  # Enabled debug
  Enabled: false
  # Disabled debug
  Disabled: false
